name: Publish Docs

on:
  push:
    branches:
      - notebooks

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1.0.0
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.6.2
      - name: Publish the documentation
        run: |
          .github/scripts/install-nbconvert.bash
          julia --project=docs -e 'using Pkg; Pkg.instantiate()'
          julia --project=docs docs/make.jl